"""De novo base parser class."""

import multiprocessing as mp
import tracemalloc

from pathlib import Path
import ahocorasick
import numpy as np
import pandas as pd
from chemical_composition.chemical_composition_kb import PROTON
from loguru import logger
from peptide_mapper.mapper import UPeptideMapper


from pyiohat.parsers.base_parser import BaseParser
from pyiohat.parsers.misc import (
    get_compositions_and_monoisotopic_masses,
    get_isotopologue_accuracy,
    init_custom_cc,
    sort_mods,
)
from pyiohat.utils import merge_and_join_dicts


class DeNovoBaseParser(BaseParser):
    """Base class of all de novo parsers."""

    def __init__(self, *args, **kwargs):
        """Initialize parser.

        Reads in data file and provides mappings.
        """
        super().__init__(*args, **kwargs)
        self.DELIMITER = self.params.get("delimiter", "<|>")
        self.PROTON = PROTON
        self.IUPAC_AAS = tuple("ACDEFGHIKLMNPQRSTUVWY")
        self.MIN_PEPTIDE_LEN = self.params.get("min_pep_length", 0)
        self.df = None

        self.non_mappable_mods = set(
            mod["name"] for mod in self.params.get("modifications", [])
        ).difference(self.mapped_mod_names)
        self.rt_truncate_precision = 2
        self.reference_dict = {
            "search_engine": None,
            "spectrum_id": None,
            "modifications": None,
            "retention_time_seconds": None,
        }
        self.required_headers = self._load_model("de_novo_parser_model.json")
        self.col_order = pd.Series(self.required_headers.keys())

    def _calc_mz(self, mass, charge):
        """Calculate mass-to-charge ratio.

        Args:
            mass (pd.Series): masses
            charge (pd.Series): charges
        Returns:
            (pd.Series): m/z
        """
        return (
            mass.astype(float) + (charge.astype(int) * self.PROTON)
        ) / charge.astype(int)

    def _calc_mass(self, mz, charge):
        """Calculate mass from mass-to-charge ratio.

        Args:
            mz (pd.Series): mass-to-charge
            charge (pd.Series): charges
        Returns:
            (pd.Series): mass
        """
        return mz.astype(float) * charge.astype(int) - (
            charge.astype(int) * self.PROTON
        )

    def clean_up_modifications(self):
        """Sanitizes modstrings generated by engine parsers.

        Modifications are sorted by position and leading, repeated or trailing delimiters are removed
        Operations are performed inplace on self.df
        """
        # Remove any trailing, leading, repeated, or only delimiters modstrings
        self.df.loc[:, "modifications"] = self.df.loc[:, "modifications"].str.replace(
            r"^;+(?=\w)|(?<=\w);+$|^;+$|;+(?=;)", "", regex=True
        )

        # Ensure same order of modifications
        self.df.loc[:, "modifications"] = (
            self.df["modifications"].fillna("").str.split(";").apply(sort_mods)
        )

    def assert_only_iupac_and_missing_aas(self):
        """Assert that only IUPAC nomenclature one letter amino acids are used in sequence.

        Non-IUPAC designations are dropped (except for selenocysteine).
        Operations are performed inplace.
        """
        self.df["sequence"] = self.df["sequence"].str.upper()
        # Added X for missing AAs
        iupac_conform_seqs = self.df["sequence"].apply(
            lambda seq: set(seq).issubset(self.IUPAC_AAS)
        )
        if any(~iupac_conform_seqs):
            self.df = self.df.loc[iupac_conform_seqs, :]
            logger.warning(
                f"sequences are not IUPAC conform. {(~iupac_conform_seqs).sum()} PSMs were dropped."
            )

    def add_protein_ids(self):
        """Add all Protein IDs that matching the sequence.

        Operations are performed inplace on self.df
        """
        if "protein_id" not in self.df.columns:
            self.df["protein_id"] = None
        peptide_mapper = UPeptideMapper(self.params["database"])

        if self.MIN_PEPTIDE_LEN > 0:
            valid_seqs = [
                seq
                for seq in self.df["sequence"]
                if isinstance(seq, str) and len(seq) >= self.MIN_PEPTIDE_LEN
            ]
            mapped_peptides = peptide_mapper.map_peptides(valid_seqs)

            peptide_mappings = [
                (
                    merge_and_join_dicts(mapped_peptides[seq], self.DELIMITER)
                    if seq in mapped_peptides
                    else {}
                )
                for seq in self.df["sequence"]
            ]
        else:
            mapped_peptides = peptide_mapper.map_peptides(self.df["sequence"].tolist())

            peptide_mappings = [
                merge_and_join_dicts(mapped_peptides[seq], self.DELIMITER)
                for seq in self.df["sequence"]
            ]

        columns_translations = {
            "start": "sequence_start",
            "end": "sequence_stop",
            "post": "sequence_post_aa",
            "id": "protein_id",
            "pre": "sequence_pre_aa",
        }
        new_columns = pd.DataFrame(peptide_mappings)
        new_columns.rename(columns=columns_translations, inplace=True)

        for col in new_columns.columns:
            self.df[col] = new_columns[col].values
        # Keep unmapped sequences but mark them to be skipped for other functions
        self.df["mapped"] = ~new_columns.isna().all(axis=1)

        unmapped_count = (~self.df["mapped"]).sum()
        if unmapped_count > 0:
            logger.warning(
                f"{unmapped_count} PSMs could not be mapped and thus certain functions will not be applied to them"
            )

        if self.style and self.style in ("pglyco_db_style_1"):
            self.df.drop("tmp_sequence", axis=1, inplace=True)
            self.df["protein_id"] = self.df.apply(
                lambda row: (
                    f"decoy_{row['protein_id']}"
                    if row["peptide_is_decoy"]
                    else row["protein_id"]
                ),
                axis=1,
            )

    def check_enzyme_specificity(self):
        """Check consistency of N/C-terminal cleavage sites.

        Calculates number of missed cleavage sites.
        Operations are performed inplace.
        """
        if self.params["enzyme"] == ".^":
            self.df.loc[:, ["enzn", "enzc"]] = True
            self.df.loc[:, "missed_cleavages"] = 0
            return None

        enzyme_pattern = self.params["enzyme"]
        integrity_strictness = self.params["terminal_cleavage_site_integrity"]
        # Initialize columns for all rows (including unmapped)
        self.df.loc[:, ["enzn", "enzc"]] = False
        self.df.loc[:, "missed_cleavages"] = 0

        # Only process mapped PSMs
        if "mapped" not in self.df.columns or not self.df["mapped"].any():
            logger.warning("No mapped PSMs found to check enzyme specificity.")
            return None

        mapped_mask = self.df["mapped"]
        mapped_df = self.df[mapped_mask]

        pren_seq = (
            pd.concat(
                [
                    mapped_df["sequence_pre_aa"].str.split(rf"{self.DELIMITER}"),
                    mapped_df["sequence"].str[:1],
                ],
                axis=1,
            )
            .explode("sequence_pre_aa")
            .sum(axis=1)
        )
        self.df.loc[mapped_mask, "enzn"] = (
            pren_seq.str.split(rf"{enzyme_pattern}").str[0].str.len() == 1
        ).groupby(pren_seq.index).agg(integrity_strictness) | (
            pren_seq.str[0] == "-"
        ).groupby(
            pren_seq.index
        ).agg(
            integrity_strictness
        )
        postc_seq = (
            pd.concat(
                [
                    mapped_df["sequence"].str[-1:],
                    mapped_df["sequence_post_aa"].str.split("<\\|>"),
                ],
                axis=1,
            )
            .explode("sequence_post_aa")
            .sum(axis=1)
        )
        self.df.loc[mapped_mask, "enzc"] = (
            postc_seq.str.split(rf"{enzyme_pattern}").str[0].str.len() == 1
        ).groupby(postc_seq.index).agg(integrity_strictness) | (
            postc_seq.str[-1] == "-"
        ).groupby(
            postc_seq.index
        ).agg(
            integrity_strictness
        )

        internal_cuts = mapped_df["sequence"].str.split(rf"{enzyme_pattern}")
        self.df.loc[mapped_mask, "missed_cleavages"] = (
            internal_cuts.apply(len)
            - internal_cuts.apply(lambda row: "" in row).astype(int)
            - 1
        )

    def calc_masses_offsets_and_composition(self):
        """Calculate chemical composition theoretical masses, and mass-to-charge ratios.

        Offsets are calculated between theoretical and experimental mass-to-charge ratio.
        Operations are performed inplace on self.df
        """
        all_compositions = {}
        for aa in self.IUPAC_AAS:
            self.cc.use(sequence=aa)
            all_compositions[aa] = self.cc.copy()
        for mod in self.mapped_mod_names:
            all_compositions[mod] = self.mod_mapper.name_to_composition(mod)[0]

        compositions, mono_masses = get_compositions_and_monoisotopic_masses(
            sequences=self.df["sequence"].to_numpy(dtype=str),
            modifications=self.df["modifications"].to_numpy(dtype=str),
            compositions=all_compositions,
            isotopic_distributions=self.cc.isotopic_distributions,
        )
        self.df.loc[:, "chemical_composition"] = compositions
        self.df.loc[:, "ucalc_mass"] = mono_masses

        with mp.Pool(
            self.params.get("cpus", 1),
            initializer=init_custom_cc,
            initargs=(
                get_isotopologue_accuracy,
                self.PROTON,
            ),
        ) as pool:
            acc = pool.starmap(
                get_isotopologue_accuracy,
                zip(
                    self.df["chemical_composition"].values,
                    self.df["charge"].astype(int).values,
                    self.df["exp_mz"].values,
                ),
            )
        self.df.loc[:, "accuracy_ppm"] = acc
        self.df.loc[:, "ucalc_mz"] = self._calc_mz(
            mass=self.df["ucalc_mass"], charge=self.df["charge"]
        )
        self.df.loc[:, "accuracy_ppm_C12"] = (
            (self.df["exp_mz"].astype(float) - self.df["ucalc_mz"])
            / self.df["ucalc_mz"]
            * 1e6
        )
        # Clear rows with non-mappable mods
        for mod in self.non_mappable_mods:
            self.df.loc[
                self.df["modifications"].str.contains(mod),
                (
                    "chemical_composition",
                    "ucalc_mass",
                    "ucalc_mz",
                    "accuracy_ppm",
                    "accuracy_ppm_C12",
                ),
            ] = np.nan
        self.df.loc[:, "exp_mass"] = self._calc_mass(
            mz=self.df["exp_mz"], charge=self.df["charge"]
        )
        self.df.loc[:, "mass_delta"] = self.df["exp_mass"] - self.df["ucalc_mass"]

    def get_meta_info(self):
        """Extract meta information.

        Experimental mass-to-charge ratios, retention times, file names,
        and spectrum titles are added.
        Operations are performed inplace on self.df
        """
        rt_lookup = self._read_meta_info_lookup_file()
        self.df["spectrum_id"] = self.df["spectrum_id"].astype(int)

        if self.style in ("comet_style_1", "omssa_style_1", "casanovo_style_1"):
            logger.warning(
                "This engine does not provide retention time information. Grouping only by Spectrum ID. This may cause problems when working with multi-file inputs."
            )
            for name, grp in self.df.groupby("spectrum_id"):
                if name not in rt_lookup:
                    raise KeyError(
                        f"Could not uniquely assign meta data to spectrum id {name}."
                    )
                meta = rt_lookup[name]
                distinct_rts = set(meta["rt"])
                if len(distinct_rts) == 1:
                    idx = 0
                    self.df.loc[
                        grp.index,
                        ("raw_data_location", "exp_mz", "retention_time_seconds"),
                    ] = [
                        meta["lineage_root"][idx],
                        meta["precursor_mz"][idx],
                        meta["rt"][idx],
                    ]
                else:
                    raise KeyError(
                        f"Could not uniquely assign meta data to spectrum id {name}."
                    )

        elif self.style == "instanovo_style_1":
            logger.warning(
                "This engine does not provide retention time information. Grouping only by MS_Level. "
                "This may cause problems when working with multi-file inputs."
            )

            # Create a sorted list of actual IDs for all MS2 spectra to map 0-based indices
            ms2_keys = sorted(
                [
                    spec_id
                    for spec_id, meta_dict in rt_lookup.items()
                    if str(meta_dict.get("ms_level", [None])[0]) == "2"
                ]
            )
            final_scan_val = getattr(self, "last_index", None)
            if final_scan_val is not None:
                if (final_scan_val + 1) != len(ms2_keys):
                    raise KeyError(
                        f"InstaNovo report contains {final_scan_val + 1} "
                        f"entries, but raw file contains {len(ms2_keys)} MS2 spectra. Could not uniquely assign meta data. "
                    )

            for name, grp in self.df.groupby("spectrum_id"):
                # Convert the InstaNovo ID (0, 1, 2...) to an integer to use as list index
                idx = int(name)

                if idx < len(ms2_keys):
                    true_spectrum_id = ms2_keys[idx]
                    meta = rt_lookup[true_spectrum_id]
                    distinct_rts = set(meta["rt"])
                    if len(distinct_rts) != 1:
                        raise KeyError(
                            f"Could not uniquely assign meta data to spectrum id {true_spectrum_id}."
                        )

                    self.df.loc[
                        grp.index,
                        (
                            "raw_data_location",
                            "exp_mz",
                            "retention_time_seconds",
                            "spectrum_id",
                        ),
                    ] = [
                        meta["lineage_root"][0],
                        meta["precursor_mz"][0],
                        meta["rt"][0],
                        true_spectrum_id,
                    ]
                else:
                    raise KeyError(
                        f"InstaNovo ID {idx} exceeds available MS2 spectra ({len(ms2_keys)})."
                    )
        else:
            self.df["retention_time_seconds"] = self.df[
                "retention_time_seconds"
            ].astype(float)
            for name, grp in self.df.groupby(["spectrum_id", "retention_time_seconds"]):
                spec_id, group_rt = name
                if spec_id not in rt_lookup:
                    raise KeyError(
                        f"Could not uniquely assign meta data to spectrum id, retention time {name}."
                    )
                meta = rt_lookup[spec_id]
                matches = [
                    i
                    for i, candidate_rt in enumerate(meta["rt"])
                    if abs(group_rt - candidate_rt) <= 10**-self.rt_truncate_precision
                ]
                if len(matches) == 1:
                    idx = matches[0]
                    self.df.loc[
                        grp.index,
                        ("raw_data_location", "exp_mz", "retention_time_seconds"),
                    ] = [
                        meta["lineage_root"][idx],
                        meta["precursor_mz"][idx],
                        meta["rt"][idx],
                    ]
                else:
                    raise KeyError(
                        f"Could not uniquely assign meta data to spectrum id, retention time {name}."
                    )

        self.df.loc[:, "spectrum_title"] = (
            self.df["raw_data_location"].apply(lambda x: Path(x).stem)
            + "."
            + self.df["spectrum_id"].astype(str)
            + "."
            + self.df["spectrum_id"].astype(str)
            + "."
            + self.df["charge"].astype(str)
        )

    def add_ranks(self):
        """Ranks are calculated based on the engine scoring column at Spectrum ID level.

        Operations are performed inplace on self.df
        """
        eng_name = self.df["search_engine"].unique()[0]
        score_col = self.metadata["validation_score_field"]
        top_is_highest = self.metadata["bigger_scores_better"]
        ranking_needs_to_be_ascending = False if top_is_highest is True else True
        self.df.loc[:, score_col] = self.df[score_col].astype(float)
        self.df.loc[:, "rank"] = (
            self.df.groupby("spectrum_id")[score_col]
            .rank(ascending=ranking_needs_to_be_ascending, method="min")
            .astype(int)
        )

    def add_decoy_identity(self):
        """Add boolean decoy state if designated decoy prefix is in Protein IDs.

        Also marks peptides which were assigned decoy but were immutable during
        target decoy generation.
        Operations are performed inplace on self.df
        """
        decoy_tag = self.params.get("decoy_tag", "decoy_")

        # Only check protein_id for mapped PSMs
        if "mapped" in self.df.columns:
            self.df.loc[:, "is_decoy"] = float("nan")
            mapped_mask = self.df["mapped"]
            self.df.loc[mapped_mask, "is_decoy"] = (
                self.df.loc[mapped_mask, "protein_id"].str.contains(decoy_tag, na=False)
            ).astype(float)

        # Glycan/peptide decoy logic applies to all rows (mapped or not)
        if "glycan_is_decoy" in self.df.columns:
            mask = self.df["glycan_is_decoy"] | self.df["peptide_is_decoy"]
            self.df.loc[mask, "is_decoy"] = True

        if self.immutable_peptides is not None:
            auto = ahocorasick.Automaton()
            for seq in self.immutable_peptides:
                auto.add_word(seq, seq)
            auto.make_automaton()
            self.df.loc[:, "is_immutable"] = [
                sum([len(match) for _, match in auto.iter_long(seq)]) == len(seq)
                for seq in self.df["sequence"]
            ]
        else:
            self.df.loc[:, "is_immutable"] = False

    def process_unify_style(self):
        tracemalloc.start()
        """Combine all additional operations that are needed to calculate new columns and sanitize the dataframe.

        Operations are performed inplace on self.df
        """

        self.df.drop_duplicates(inplace=True, ignore_index=True)
        self.clean_up_modifications()
        self.assert_only_iupac_and_missing_aas()
        self.add_protein_ids()
        self.get_meta_info()
        self.calc_masses_offsets_and_composition()
        self.check_enzyme_specificity()
        self.add_ranks()
        self.add_decoy_identity()
        self.sanitize()
