name: Build Docs

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install pyiohat
      run: pip install .
    - name: Install Sphinx
      run: |
        pip install sphinx
        pip install sphinx-rtd-theme
    - name: Build documentation using Sphinx
      run: |
        mkdir static_docs
        mv docs/*.rst static_docs/ || true
        rm -r docs
        mkdir docs
        cd docs
        sphinx-quickstart -p pyiohat -a "$(awk '{print $1,$2}' ../AUTHORS.TXT | paste -s -d, - | sed -e 's/,/, /g')" -v ${{ github.ref_name }} -l en --no-sep -q --ext-autodoc --extensions sphinx_rtd_theme
        mv ../static_docs/*.rst . || true
        rm -r ../static_docs
        sed -E "s/(html_theme =) .*/\1 'sphinx_rtd_theme'/" conf.py > tmp.py
        mv tmp.py conf.py
        sphinx-apidoc -o source/ ../pyiohat
        make html
    - name: Checkout Github Pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit and push documentation changes
      run: |
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        git push